name: nChannels
main: no.runsafe.nchannels.nChannels
version: 1.0.@BUILD@
authors: [mortenn, Kruithne]
depend: [nChat]
description:
commands:
  channel:
    description: Manage chat channels
    aliases: [c]
